services:

  proxy:
    image: traefik:v2.5
    container_name: proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8090:9090"
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `a-traefik-public`)

      - --providers.docker.exposedbydefault=false

      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443

      - --accesslog
      - --log
      - --log.level=DEBUG

      - --api
      - --api.insecure=true
    labels:
      # Enable Traefik for this service, to make it available in the public network
      - traefik.enable=true
      - traefik.constraint-label=a-traefik-public
      # Dummy https-redirect middleware that doesn't really redirect, only to
      # allow running it locally
      - traefik.http.middlewares.https-redirect.contenttype.autodetect=false
    networks:
      - a-traefik-public

  #
  # May be overridden for dev purposes
  #

  backend:
    extends:
      file: ./../backend/.docker/compose.override.yml
      service: backend
    restart: no

  db:
    extends:
      file: ./../backend/.docker/compose.override.yml
      service: db

  pgadmin:
    extends:
      file: ./../backend/.docker/compose.override.yml
      service: pgadmin

  frontend:
    extends:
      file: ./../frontend/.docker/compose.override.yml
      service: frontend
    restart: no

networks:
  a-traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false